title: Kheeran K. Naidu
description: My current research interest is broadly in the design and analysis of algorithms for processing massive datasets. I obtained my PhD in Computer Science at the University of Bristol under the supervision of Christian Konrad. During this time, I tackled graph problems in the data streaming setting.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kheerannaidu.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Kheeran K. Naidu # add your name
author-img: kheeran.jpg # add your photo
# about-author: Seeking a postdoc in a theory group to tackle research questions pertaining to sublinear algorithms and beyond. # add description
position: PhD in Computer Science
location: Algorithms and Complexity Group, University of Bristol
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: # add your Github handle
social-linkedin: kheeran # add your Linkedin handle
social-email: kheeran.naidu@gmail.com # add your Email address

# Disqus
disqus-identifier: False # add your discus identifier

# Tracker
analytics: UA-105864269-3 # add Google Analytics Track ID

# Build Settings
markdown: kramdown
kramdown:
  math_engine: katex
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 10
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
